spring:
  datasource:
    url: jdbc:hsqldb:file:db/service_db
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

